"use client";
import { useEffect, useRef, useState } from 'react';
import { Input, BlobSource, MATROSKA, WEBM, VideoSampleSink } from 'mediabunny';
import { ArrowLeft, ArrowRight, Check, Download, Film, FolderOpen, Plus, Settings2, Undo2, X } from 'lucide-react';

type ClassDef = { name: string; key: string };
type Row = { reviewed: boolean; flags: number[] };
const defaults: ClassDef[] = [{name:'異常クラス A',key:'1'},{name:'異常クラス B',key:'2'},{name:'異常クラス C',key:'3'}];
const quote = (s: unknown) => '"' + String(s).replace(/"/g,'""') + '"';
export default function Home(){
 const [classes,setClasses]=useState(defaults), [rows,setRows]=useState<Record<number,Row>>({}), [times,setTimes]=useState<number[]>([]), [index,setIndex]=useState(0), [file,setFile]=useState<File|null>(null), [busy,setBusy]=useState(false), [rendering,setRendering]=useState(false), [message,setMessage]=useState(''), [settings,setSettings]=useState(false), [draft,setDraft]=useState(defaults), [configError,setConfigError]=useState(''), [scanned,setScanned]=useState(0);
 const canvas=useRef<HTMLCanvasElement>(null), picker=useRef<HTMLInputElement>(null), input=useRef<Input|null>(null), sink=useRef<VideoSampleSink|null>(null), history=useRef<{index:number; row:Row|undefined}[]>([]), loadId=useRef(0), ready=useRef(false);
 const agentState=useRef({frame:index,total:times.length,rows,classes}); agentState.current={frame:index,total:times.length,rows,classes};
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_annotation_progress',description:'Read the current frame, annotation classes and reviewed frame count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(args:unknown)=>{if(!args||typeof args!=='object'||Object.keys(args).length)throw Error('Expected an empty object');const s=agentState.current;return {frame:s.frame,total:s.total,reviewed:Object.values(s.rows).filter(r=>r.reviewed).length,classes:s.classes,current:s.rows[s.frame]||null}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 const row=rows[index]; const reviewed=Object.values(rows).filter(r=>r.reviewed).length; const complete=times.length>0&&reviewed===times.length; const active=times.length>0&&!busy&&!rendering; const storageKey=file?`frame:v1:${file.name}:${file.size}:${file.lastModified}`:'';
 useEffect(()=>()=>{loadId.current++;input.current?.dispose()},[]);
 useEffect(()=>{if(!storageKey||!times.length)return; const t=setTimeout(()=>{try{localStorage.setItem(storageKey,JSON.stringify({classes,rows,index}));}catch{setMessage('自動保存できません。CSVを出力して結果を保存してください。')}},300);return()=>clearTimeout(t)},[storageKey,classes,rows,index,times.length]);
 async function openFile(f:File){
  if(busy)return; const id=++loadId.current; ready.current=false;setBusy(true);setScanned(0);setMessage('');setTimes([]);setRows({});setIndex(0);setFile(f);history.current=[];input.current?.dispose();
  try{
   if(!('VideoDecoder' in window))throw Error('このブラウザでは動画をデコードできません。最新版のChromeまたはEdgeを使用してください。');
   const media=new Input({source:new BlobSource(f),formats:[MATROSKA,WEBM]}); input.current=media;
   const track=await media.getPrimaryVideoTrack(); if(!track)throw Error('動画トラックがありません。');if(await track.getCodec()!=='vp9')throw Error('VP9形式のMKV / WebMを選択してください。');if(!await track.canDecode())throw Error('この動画のVP9設定は、この環境ではデコードできません。');
   const decoder=new VideoSampleSink(track);sink.current=decoder; const timestamps:number[]=[];
   for await(const sample of decoder.samples()) { if(id!==loadId.current){sample.close();return} timestamps.push(sample.timestamp);sample.close();if(timestamps.length%120===0){setScanned(timestamps.length);await new Promise(r=>setTimeout(r,0));} }
   if(!timestamps.length)throw Error('表示できるフレームがありません。');
   setTimes(timestamps);
   const saved=localStorage.getItem(`frame:v1:${f.name}:${f.size}:${f.lastModified}`);
   if(saved){try{const s=JSON.parse(saved);if(Array.isArray(s.classes)&&s.classes.length&&s.classes.every((c:ClassDef)=>typeof c.name==='string'&&typeof c.key==='string')&&s.rows&&typeof s.rows==='object'){setClasses(s.classes);setRows(s.rows);setIndex(Math.min(Math.max(Number(s.index)||0,0),timestamps.length-1));setMessage('この動画の前回の作業を復元しました。')}}catch{ /* Ignore invalid local state. */ }}
  }catch(e){setMessage(e instanceof Error?e.message:'動画を読み込めませんでした。');input.current?.dispose();sink.current=null;}
  finally{if(id===loadId.current)setBusy(false)}
 }
 useEffect(()=>{if(!times.length||!sink.current)return;let cancelled=false;ready.current=false;setRendering(true);const decoder=sink.current;void(async()=>{try{const sample=await decoder.getSample(times[index]);if(!sample)throw Error('フレームを取得できません。');try{if(!cancelled&&canvas.current){const c=canvas.current;c.width=sample.displayWidth;c.height=sample.displayHeight;sample.draw(c.getContext('2d')!,0,0);ready.current=true;}}finally{sample.close()}}catch(e){if(!cancelled)setMessage(e instanceof Error?e.message:'表示に失敗しました。')}finally{if(!cancelled)setRendering(false)}})();return()=>{cancelled=true}},[index,times]);
 function update(next:Row){history.current.push({index,row:rows[index]});setRows(r=>({...r,[index]:next}))}
 function toggle(n:number){if(!active||!ready.current)return;const flags=[...(row?.flags||classes.map(()=>0))];flags[n]=flags[n]?0:1;update({reviewed:row?.reviewed||false,flags})}
 function move(delta:number){if(!active||!ready.current)return;ready.current=false;const next=Math.min(times.length-1,Math.max(0,index+delta));if(next===index){ready.current=true;return}setIndex(next)}
 function confirm(){if(!active||!ready.current)return;update({reviewed:true,flags:row?.flags||classes.map(()=>0)});if(index<times.length-1)move(1);else setMessage('最終フレームです。未確認がなくなったらCSVを出力できます。')}
 function undo(){if(!active)return;const h=history.current.pop();if(!h)return;ready.current=false;setIndex(h.index);if(h.index===index)ready.current=true;setRows(r=>{const next={...r};if(h.row)next[h.index]=h.row;else delete next[h.index];return next})}
 function exportCsv(){if(!times.length||busy)return;const lines=[['frame','timestamp_sec','reviewed',...classes.map(c=>c.name)].map(quote).join(','),...times.map((t,i)=>[i,t.toFixed(6),rows[i]?.reviewed?1:0,...classes.map((_,n)=>rows[i]?.flags[n]||0)].join(','))];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${file?.name.replace(/\.[^.]+$/,'')||'labels'}${complete?'':'_partial'}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(complete?'全フレームのCSVを出力しました。':'途中結果を出力しました。未確認フレームは reviewed=0 です。')}
 useEffect(()=>{function key(e:KeyboardEvent){if(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable=true]'))return;if(settings)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return}if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key.toLowerCase()==='o'){e.preventDefault();picker.current?.click()}else if(e.key==='ArrowRight'){e.preventDefault();move(1)}else if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}else if(e.key==='Enter'&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();confirm()}else if(e.key.toLowerCase()==='e'){e.preventDefault();exportCsv()}else{const n=classes.findIndex(c=>c.key.toLowerCase()===e.key.toLowerCase());if(n>=0&&!e.repeat){e.preventDefault();toggle(n)}}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 function saveClasses(){const names=draft.map(c=>c.name.trim()),keys=draft.map(c=>c.key.toLowerCase());if(names.some(n=>!n)||new Set(names).size!==names.length||new Set(keys).size!==keys.length||keys.some(k=>! /^[a-z0-9]$/.test(k)||['o','e'].includes(k))){setConfigError('名前は重複なし、キーは O・E 以外の重複しない英数字1文字にしてください。');return}setClasses(draft.map((c,i)=>({...c,name:names[i],key:keys[i]})));setSettings(false);history.current=[]}
 return <main>
  <header><a className="brand" href="/" aria-label="Frame ホーム"><span className="brand-icon"><Film size={21}/></span>frame<span className="brand-sub">ANNOTATOR</span></a><div className="header-actions"><span className="local-label">ローカル処理 · VP9 / MKV</span><button onClick={()=>picker.current?.click()} disabled={busy}><FolderOpen size={16}/>動画を開く<kbd>O</kbd></button><button className="primary" disabled={!times.length||busy} onClick={exportCsv}><Download size={16}/>{complete?'CSVを書き出す':'CSV出力'}<kbd>E</kbd></button></div></header>
  <input ref={picker} type="file" accept=".mkv,.webm" className="file-input" aria-label="動画を選択" onChange={e=>{const f=e.target.files?.[0];if(f)void openFile(f);e.target.value=''}}/>
  <div className="workspace-heading"><div><p className="eyebrow">FRAME-BY-FRAME LABELING</p><h1>{file?.name||'アノテーション workspace'}</h1></div><span className="pill">{busy?'読み込み中':complete?'確認完了':times.length?'作業中':'動画未選択'}</span></div>
  <div className="workspace"><section className="viewer-panel"><div className="viewer-top"><span><Film size={15}/>VIDEO</span><span>{times.length?`${times.length.toLocaleString()} frames`:'MKV / WebM · VP9'}</span></div><div className="screen" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)void openFile(f)}}>
   <canvas ref={canvas} hidden={!times.length} aria-label={`フレーム ${index}`}/>
   {!times.length&&<div className="empty"><div className="empty-icon"><Film size={32}/></div><h2>{busy?'フレームを確認しています':'動画から、ひとつずつ。'}</h2><p>{busy?`${scanned.toLocaleString()} フレームを読み取り済み`:'ここに動画をドロップ、またはファイルを選択'}</p>{busy?<p className="muted">正確なフレーム番号のため、初回は動画全体を読み取ります。</p>:<button onClick={()=>picker.current?.click()}><Plus size={17}/>動画を選択する</button>}<small>動画はこのPC内で処理されます</small></div>}
   {!!times.length&&<span className="frame-overlay">FRAME {String(index).padStart(6,'0')}{rendering?' · 読み込み中':''}</span>}
  </div><div className="transport"><div className="frame-number"><span>FRAME</span><strong>{times.length?String(index).padStart(6,'0'):'—'}</strong><small>/ {times.length?String(times.length-1).padStart(6,'0'):'—'}</small></div><div className="step-controls"><button aria-label="前のフレーム" disabled={!active||index===0} onClick={()=>move(-1)}><ArrowLeft size={18}/></button><span>1 frame</span><button aria-label="次のフレーム" disabled={!active||index===times.length-1} onClick={()=>move(1)}><ArrowRight size={18}/></button></div><span className="timestamp">{times.length?times[index].toFixed(6):'0.000000'} s</span></div>
  <div className="progress-area"><div><span>確認済みのフレーム</span><strong>{reviewed.toLocaleString()} <span>/ {times.length.toLocaleString()}</span></strong></div><progress max={times.length||1} value={reviewed}/><div className="progress-bottom"><span>{complete?'すべて確認済みです。CSVを出力できます。':'Enter で確認済みにして、次のフレームへ'}</span><span>{times.length?Math.round(reviewed/times.length*100):0}%</span></div></div></section>
  <aside><div className="panel-heading"><div><p className="eyebrow">ANNOTATION</p><h2>異常クラス</h2></div><button className="icon-button" aria-label="クラスとキーの設定" onClick={()=>{setDraft(classes.map(c=>({...c})));setConfigError('');setSettings(true)}}><Settings2 size={18}/></button></div><p className="panel-description">該当するクラスをオンにします。<br/>複数のクラスを同時に選択できます。</p><div className="class-list">{classes.map((c,n)=><button key={n} className={`class-card ${row?.flags[n]?'selected':''}`} aria-pressed={!!row?.flags[n]} disabled={!active} onClick={()=>toggle(n)}><kbd>{c.key.toUpperCase()}</kbd><span>{c.name}</span><b>{row?.flags[n]||0}</b></button>)}</div><div className="review-status"><span className={row?.reviewed?'status-reviewed':''}>{row?.reviewed?<Check size={15}/>:<span className="status-dot"/>}{row?.reviewed?'確認済み':'未確認'}</span><span>{row?.flags.some(Boolean)?'異常あり':'フラグなし'}</span></div><button className="primary confirm" disabled={!active} onClick={confirm}><Check size={18}/>確認して次へ<kbd>Enter</kbd></button><button className="undo" disabled={!active||!history.current.length} onClick={undo}><Undo2 size={15}/>ラベル変更を元に戻す<small>Ctrl Z</small></button><div className="note">異常がない場合は、すべて0のまま<br/>確認してください。</div></aside></div>
  {message&&<div role="status" className="message">{message}<button aria-label="通知を閉じる" onClick={()=>setMessage('')}><X size={15}/></button></div>}
  <footer><span><kbd>←</kbd><kbd>→</kbd> フレーム移動</span><span><kbd>1</kbd>–<kbd>9</kbd> クラス切り替え（変更可）</span><span><kbd>Enter</kbd> 確認・次へ</span><span className="autosave">作業はブラウザに自動保存</span></footer>
  {settings&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="クラス設定"><div className="panel-heading"><h2>クラスとキー</h2><button aria-label="設定を閉じる" onClick={()=>setSettings(false)}><X size={18}/></button></div><p>ラベル付け開始後は、クラスの追加・削除はできません。</p>{draft.map((c,n)=><div className="config-row" key={n}><input aria-label={`クラス${n+1}の名前`} value={c.name} onChange={e=>setDraft(d=>d.map((v,i)=>i===n?{...v,name:e.target.value}:v))}/><input aria-label={`クラス${n+1}のキー`} className="key-input" maxLength={1} value={c.key} onChange={e=>setDraft(d=>d.map((v,i)=>i===n?{...v,key:e.target.value}:v))}/><button aria-label={`クラス${n+1}を削除`} disabled={Object.keys(rows).length>0||draft.length===1} onClick={()=>setDraft(d=>d.filter((_,i)=>i!==n))}><X size={16}/></button></div>)}{configError&&<p role="alert">{configError}</p>}<div className="modal-actions"><button disabled={draft.length>=9||Object.keys(rows).length>0} onClick={()=>setDraft(d=>[...d,{name:`異常クラス ${d.length+1}`,key:'123456789'.split('').find(k=>!d.some(c=>c.key===k))||''}])}><Plus size={16}/>クラスを追加</button><button className="primary" onClick={saveClasses}>保存</button></div></section></div>}
 </main>
}


